//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.UsersLaptopService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Laptops", Namespace="http://schemas.datacontract.org/2004/07/Models")]
    [System.SerializableAttribute()]
    public partial class Laptops : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HardDiskField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LaptopIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProcessorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ScreenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Brand {
            get {
                return this.BrandField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandField, value) != true)) {
                    this.BrandField = value;
                    this.RaisePropertyChanged("Brand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HardDisk {
            get {
                return this.HardDiskField;
            }
            set {
                if ((object.ReferenceEquals(this.HardDiskField, value) != true)) {
                    this.HardDiskField = value;
                    this.RaisePropertyChanged("HardDisk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LaptopID {
            get {
                return this.LaptopIDField;
            }
            set {
                if ((this.LaptopIDField.Equals(value) != true)) {
                    this.LaptopIDField = value;
                    this.RaisePropertyChanged("LaptopID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OS {
            get {
                return this.OSField;
            }
            set {
                if ((object.ReferenceEquals(this.OSField, value) != true)) {
                    this.OSField = value;
                    this.RaisePropertyChanged("OS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Processor {
            get {
                return this.ProcessorField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcessorField, value) != true)) {
                    this.ProcessorField = value;
                    this.RaisePropertyChanged("Processor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Ram {
            get {
                return this.RamField;
            }
            set {
                if ((this.RamField.Equals(value) != true)) {
                    this.RamField = value;
                    this.RaisePropertyChanged("Ram");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Screen {
            get {
                return this.ScreenField;
            }
            set {
                if ((this.ScreenField.Equals(value) != true)) {
                    this.ScreenField = value;
                    this.RaisePropertyChanged("Screen");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UsersLaptopService.IUsersLaptopServiceOf_Laptops")]
    public interface IUsersLaptopServiceOf_Laptops {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersLaptopServiceOf_Laptops/GetAllUserLaptops", ReplyAction="http://tempuri.org/IUsersLaptopServiceOf_Laptops/GetAllUserLaptopsResponse")]
        WebStore.UsersLaptopService.Laptops[] GetAllUserLaptops(string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersLaptopServiceOf_Laptops/GetAllUserLaptops", ReplyAction="http://tempuri.org/IUsersLaptopServiceOf_Laptops/GetAllUserLaptopsResponse")]
        System.Threading.Tasks.Task<WebStore.UsersLaptopService.Laptops[]> GetAllUserLaptopsAsync(string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersLaptopServiceOf_Laptops/SetLaptop", ReplyAction="http://tempuri.org/IUsersLaptopServiceOf_Laptops/SetLaptopResponse")]
        bool SetLaptop(string userid, int laptopid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersLaptopServiceOf_Laptops/SetLaptop", ReplyAction="http://tempuri.org/IUsersLaptopServiceOf_Laptops/SetLaptopResponse")]
        System.Threading.Tasks.Task<bool> SetLaptopAsync(string userid, int laptopid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsersLaptopServiceOf_LaptopsChannel : WebStore.UsersLaptopService.IUsersLaptopServiceOf_Laptops, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsersLaptopServiceOf_LaptopsClient : System.ServiceModel.ClientBase<WebStore.UsersLaptopService.IUsersLaptopServiceOf_Laptops>, WebStore.UsersLaptopService.IUsersLaptopServiceOf_Laptops {
        
        public UsersLaptopServiceOf_LaptopsClient() {
        }
        
        public UsersLaptopServiceOf_LaptopsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsersLaptopServiceOf_LaptopsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsersLaptopServiceOf_LaptopsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsersLaptopServiceOf_LaptopsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebStore.UsersLaptopService.Laptops[] GetAllUserLaptops(string userid) {
            return base.Channel.GetAllUserLaptops(userid);
        }
        
        public System.Threading.Tasks.Task<WebStore.UsersLaptopService.Laptops[]> GetAllUserLaptopsAsync(string userid) {
            return base.Channel.GetAllUserLaptopsAsync(userid);
        }
        
        public bool SetLaptop(string userid, int laptopid) {
            return base.Channel.SetLaptop(userid, laptopid);
        }
        
        public System.Threading.Tasks.Task<bool> SetLaptopAsync(string userid, int laptopid) {
            return base.Channel.SetLaptopAsync(userid, laptopid);
        }
    }
}
